### ISSUE TITLE
Convertion doubt

### ISSUE THREAD

**Issue by russellhoff** [Berico-Technologies/Geo-Coordinate-Conversion-Java#6]
Can I convert UTM coordinates to WGS84 using this library? Thanks in advance

**Comment by steve-ttt** [comment]
Sorry for the n00b question but how do I build this so I can use it in my project

**Comment by russellhoff** [comment]
You could add this project as a Maven dependency in your project. To add Github projects as Maven dependencies, there is Jitpack manager. 

Hope this helps.
